### ISSUE TITLE
#thehub will not open in Expo client

### ISSUE THREAD

**Issue by langhisc** [fsapprenticeship/fsa-hub#80]
Environment:
• iOS software version 12.1.2 (16C101)
• Expo iOS client version 2.9.0.103161

Steps to reproduce:
1.  Visit in Safari on Mac: https://expo.io/@fullstackapprentice/thehub
2.  Enter phone number in "Request a link" box
3.  Receive SMS containing link: exp://exp.host/@fullstackapprentice/thehub
4.  Tap link on iPhone to open
5.  Observe that iPhone switches to Expo client app
6.  Observe error screen (see attached image)

![img_5376](https://user-images.githubusercontent.com/4576745/50787715-0b7cb180-126c-11e9-9c0c-8dbf6991c230.PNG)

**Comment by mikhael28** [comment]
@langhisc after working with a few people who also had trouble with iOS, I have come to the conclusion that Apple has made it more difficult for anyone to load anything on Expo that isn't on Android. My theory is that, since Apple wants 30% of all the transaction fees on their platform, they don't like something like Expo to come and potentially take that away.

**Comment by langhisc** [comment]
Thanks for the update.  That seems plausible.

**Comment by mikhael28** [comment]
@langhisc I'm closing this issue, as I have discovered that apple indeed is a POS. You should be able to access this through the local development environment however (or on an Xcode emulator)
